// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/game.proto

package game

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenSessionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSessionRequest) Reset()         { *m = OpenSessionRequest{} }
func (m *OpenSessionRequest) String() string { return proto.CompactTextString(m) }
func (*OpenSessionRequest) ProtoMessage()    {}
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{0}
}

func (m *OpenSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenSessionRequest.Unmarshal(m, b)
}
func (m *OpenSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenSessionRequest.Marshal(b, m, deterministic)
}
func (m *OpenSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSessionRequest.Merge(m, src)
}
func (m *OpenSessionRequest) XXX_Size() int {
	return xxx_messageInfo_OpenSessionRequest.Size(m)
}
func (m *OpenSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSessionRequest proto.InternalMessageInfo

func (m *OpenSessionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type OpenSessionResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Table                *Table   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSessionResponse) Reset()         { *m = OpenSessionResponse{} }
func (m *OpenSessionResponse) String() string { return proto.CompactTextString(m) }
func (*OpenSessionResponse) ProtoMessage()    {}
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{1}
}

func (m *OpenSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenSessionResponse.Unmarshal(m, b)
}
func (m *OpenSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenSessionResponse.Marshal(b, m, deterministic)
}
func (m *OpenSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSessionResponse.Merge(m, src)
}
func (m *OpenSessionResponse) XXX_Size() int {
	return xxx_messageInfo_OpenSessionResponse.Size(m)
}
func (m *OpenSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSessionResponse proto.InternalMessageInfo

func (m *OpenSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *OpenSessionResponse) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *OpenSessionResponse) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

type Table struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Trump                string         `protobuf:"bytes,2,opt,name=trump,proto3" json:"trump,omitempty"`
	Turn                 uint32         `protobuf:"varint,3,opt,name=turn,proto3" json:"turn,omitempty"`
	TableCards           string         `protobuf:"bytes,4,opt,name=table_cards,json=tableCards,proto3" json:"table_cards,omitempty"`
	ClubPlayer           uint32         `protobuf:"varint,5,opt,name=club_player,json=clubPlayer,proto3" json:"club_player,omitempty"`
	Dealer               uint32         `protobuf:"varint,6,opt,name=dealer,proto3" json:"dealer,omitempty"`
	Team_1Score          uint32         `protobuf:"varint,7,opt,name=team_1_score,json=team1Score,proto3" json:"team_1_score,omitempty"`
	Team_2Score          uint32         `protobuf:"varint,8,opt,name=team_2_score,json=team2Score,proto3" json:"team_2_score,omitempty"`
	Team_1Total          uint32         `protobuf:"varint,9,opt,name=team_1_total,json=team1Total,proto3" json:"team_1_total,omitempty"`
	Team_2Total          uint32         `protobuf:"varint,10,opt,name=team_2_total,json=team2Total,proto3" json:"team_2_total,omitempty"`
	Participants         []*Participant `protobuf:"bytes,11,rep,name=participants,proto3" json:"participants,omitempty"`
	Bet                  uint32         `protobuf:"varint,12,opt,name=bet,proto3" json:"bet,omitempty"`
	UnitType             string         `protobuf:"bytes,13,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{2}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Table) GetTrump() string {
	if m != nil {
		return m.Trump
	}
	return ""
}

func (m *Table) GetTurn() uint32 {
	if m != nil {
		return m.Turn
	}
	return 0
}

func (m *Table) GetTableCards() string {
	if m != nil {
		return m.TableCards
	}
	return ""
}

func (m *Table) GetClubPlayer() uint32 {
	if m != nil {
		return m.ClubPlayer
	}
	return 0
}

func (m *Table) GetDealer() uint32 {
	if m != nil {
		return m.Dealer
	}
	return 0
}

func (m *Table) GetTeam_1Score() uint32 {
	if m != nil {
		return m.Team_1Score
	}
	return 0
}

func (m *Table) GetTeam_2Score() uint32 {
	if m != nil {
		return m.Team_2Score
	}
	return 0
}

func (m *Table) GetTeam_1Total() uint32 {
	if m != nil {
		return m.Team_1Total
	}
	return 0
}

func (m *Table) GetTeam_2Total() uint32 {
	if m != nil {
		return m.Team_2Total
	}
	return 0
}

func (m *Table) GetParticipants() []*Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *Table) GetBet() uint32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func (m *Table) GetUnitType() string {
	if m != nil {
		return m.UnitType
	}
	return ""
}

type Player struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CloseSessionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSessionRequest) Reset()         { *m = CloseSessionRequest{} }
func (m *CloseSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CloseSessionRequest) ProtoMessage()    {}
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{4}
}

func (m *CloseSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseSessionRequest.Unmarshal(m, b)
}
func (m *CloseSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseSessionRequest.Marshal(b, m, deterministic)
}
func (m *CloseSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSessionRequest.Merge(m, src)
}
func (m *CloseSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CloseSessionRequest.Size(m)
}
func (m *CloseSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSessionRequest proto.InternalMessageInfo

type CloseSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSessionResponse) Reset()         { *m = CloseSessionResponse{} }
func (m *CloseSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CloseSessionResponse) ProtoMessage()    {}
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{5}
}

func (m *CloseSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseSessionResponse.Unmarshal(m, b)
}
func (m *CloseSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseSessionResponse.Marshal(b, m, deterministic)
}
func (m *CloseSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSessionResponse.Merge(m, src)
}
func (m *CloseSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CloseSessionResponse.Size(m)
}
func (m *CloseSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSessionResponse proto.InternalMessageInfo

// table
type CreateTableRequest struct {
	UnitType             string   `protobuf:"bytes,1,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	Bet                  uint32   `protobuf:"varint,2,opt,name=bet,proto3" json:"bet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTableRequest) Reset()         { *m = CreateTableRequest{} }
func (m *CreateTableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTableRequest) ProtoMessage()    {}
func (*CreateTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{6}
}

func (m *CreateTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTableRequest.Unmarshal(m, b)
}
func (m *CreateTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTableRequest.Marshal(b, m, deterministic)
}
func (m *CreateTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTableRequest.Merge(m, src)
}
func (m *CreateTableRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTableRequest.Size(m)
}
func (m *CreateTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTableRequest proto.InternalMessageInfo

func (m *CreateTableRequest) GetUnitType() string {
	if m != nil {
		return m.UnitType
	}
	return ""
}

func (m *CreateTableRequest) GetBet() uint32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

type CreateTableResponse struct {
	TableId              string   `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	UnitType             string   `protobuf:"bytes,2,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	Bet                  uint32   `protobuf:"varint,3,opt,name=bet,proto3" json:"bet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTableResponse) Reset()         { *m = CreateTableResponse{} }
func (m *CreateTableResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTableResponse) ProtoMessage()    {}
func (*CreateTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{7}
}

func (m *CreateTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTableResponse.Unmarshal(m, b)
}
func (m *CreateTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTableResponse.Marshal(b, m, deterministic)
}
func (m *CreateTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTableResponse.Merge(m, src)
}
func (m *CreateTableResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTableResponse.Size(m)
}
func (m *CreateTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTableResponse proto.InternalMessageInfo

func (m *CreateTableResponse) GetTableId() string {
	if m != nil {
		return m.TableId
	}
	return ""
}

func (m *CreateTableResponse) GetUnitType() string {
	if m != nil {
		return m.UnitType
	}
	return ""
}

func (m *CreateTableResponse) GetBet() uint32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

type JoinTableRequest struct {
	TableId              string   `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinTableRequest) Reset()         { *m = JoinTableRequest{} }
func (m *JoinTableRequest) String() string { return proto.CompactTextString(m) }
func (*JoinTableRequest) ProtoMessage()    {}
func (*JoinTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{8}
}

func (m *JoinTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinTableRequest.Unmarshal(m, b)
}
func (m *JoinTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinTableRequest.Marshal(b, m, deterministic)
}
func (m *JoinTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinTableRequest.Merge(m, src)
}
func (m *JoinTableRequest) XXX_Size() int {
	return xxx_messageInfo_JoinTableRequest.Size(m)
}
func (m *JoinTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinTableRequest proto.InternalMessageInfo

func (m *JoinTableRequest) GetTableId() string {
	if m != nil {
		return m.TableId
	}
	return ""
}

type JoinTableResponse struct {
	Table                *Table   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinTableResponse) Reset()         { *m = JoinTableResponse{} }
func (m *JoinTableResponse) String() string { return proto.CompactTextString(m) }
func (*JoinTableResponse) ProtoMessage()    {}
func (*JoinTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{9}
}

func (m *JoinTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinTableResponse.Unmarshal(m, b)
}
func (m *JoinTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinTableResponse.Marshal(b, m, deterministic)
}
func (m *JoinTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinTableResponse.Merge(m, src)
}
func (m *JoinTableResponse) XXX_Size() int {
	return xxx_messageInfo_JoinTableResponse.Size(m)
}
func (m *JoinTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinTableResponse proto.InternalMessageInfo

func (m *JoinTableResponse) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

type Participant struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order                uint32   `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Cards                string   `protobuf:"bytes,3,opt,name=cards,proto3" json:"cards,omitempty"`
	CardsCount           uint32   `protobuf:"varint,4,opt,name=cards_count,json=cardsCount,proto3" json:"cards_count,omitempty"`
	Player               *Player  `protobuf:"bytes,5,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Participant) Reset()         { *m = Participant{} }
func (m *Participant) String() string { return proto.CompactTextString(m) }
func (*Participant) ProtoMessage()    {}
func (*Participant) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{10}
}

func (m *Participant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participant.Unmarshal(m, b)
}
func (m *Participant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participant.Marshal(b, m, deterministic)
}
func (m *Participant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participant.Merge(m, src)
}
func (m *Participant) XXX_Size() int {
	return xxx_messageInfo_Participant.Size(m)
}
func (m *Participant) XXX_DiscardUnknown() {
	xxx_messageInfo_Participant.DiscardUnknown(m)
}

var xxx_messageInfo_Participant proto.InternalMessageInfo

func (m *Participant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Participant) GetOrder() uint32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *Participant) GetCards() string {
	if m != nil {
		return m.Cards
	}
	return ""
}

func (m *Participant) GetCardsCount() uint32 {
	if m != nil {
		return m.CardsCount
	}
	return 0
}

func (m *Participant) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type MakeMoveRequest struct {
	TableId              string   `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Card                 string   `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeMoveRequest) Reset()         { *m = MakeMoveRequest{} }
func (m *MakeMoveRequest) String() string { return proto.CompactTextString(m) }
func (*MakeMoveRequest) ProtoMessage()    {}
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{11}
}

func (m *MakeMoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeMoveRequest.Unmarshal(m, b)
}
func (m *MakeMoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeMoveRequest.Marshal(b, m, deterministic)
}
func (m *MakeMoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeMoveRequest.Merge(m, src)
}
func (m *MakeMoveRequest) XXX_Size() int {
	return xxx_messageInfo_MakeMoveRequest.Size(m)
}
func (m *MakeMoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeMoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeMoveRequest proto.InternalMessageInfo

func (m *MakeMoveRequest) GetTableId() string {
	if m != nil {
		return m.TableId
	}
	return ""
}

func (m *MakeMoveRequest) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

type MakeMoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeMoveResponse) Reset()         { *m = MakeMoveResponse{} }
func (m *MakeMoveResponse) String() string { return proto.CompactTextString(m) }
func (*MakeMoveResponse) ProtoMessage()    {}
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5309ac3f9cbe5f84, []int{12}
}

func (m *MakeMoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeMoveResponse.Unmarshal(m, b)
}
func (m *MakeMoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeMoveResponse.Marshal(b, m, deterministic)
}
func (m *MakeMoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeMoveResponse.Merge(m, src)
}
func (m *MakeMoveResponse) XXX_Size() int {
	return xxx_messageInfo_MakeMoveResponse.Size(m)
}
func (m *MakeMoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeMoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeMoveResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*OpenSessionRequest)(nil), "OpenSessionRequest")
	proto.RegisterType((*OpenSessionResponse)(nil), "OpenSessionResponse")
	proto.RegisterType((*Table)(nil), "Table")
	proto.RegisterType((*Player)(nil), "Player")
	proto.RegisterType((*CloseSessionRequest)(nil), "CloseSessionRequest")
	proto.RegisterType((*CloseSessionResponse)(nil), "CloseSessionResponse")
	proto.RegisterType((*CreateTableRequest)(nil), "CreateTableRequest")
	proto.RegisterType((*CreateTableResponse)(nil), "CreateTableResponse")
	proto.RegisterType((*JoinTableRequest)(nil), "JoinTableRequest")
	proto.RegisterType((*JoinTableResponse)(nil), "JoinTableResponse")
	proto.RegisterType((*Participant)(nil), "Participant")
	proto.RegisterType((*MakeMoveRequest)(nil), "MakeMoveRequest")
	proto.RegisterType((*MakeMoveResponse)(nil), "MakeMoveResponse")
}

func init() { proto.RegisterFile("proto/game.proto", fileDescriptor_5309ac3f9cbe5f84) }

var fileDescriptor_5309ac3f9cbe5f84 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4f, 0x6b, 0xdb, 0x4c,
	0x10, 0xc6, 0xb1, 0x1d, 0x2b, 0xf6, 0xc8, 0x79, 0x5f, 0x67, 0xed, 0x04, 0xd5, 0x6d, 0x89, 0xd1,
	0x29, 0x94, 0x76, 0x53, 0xab, 0x97, 0x42, 0x2f, 0x05, 0x1f, 0x4a, 0x0a, 0xa1, 0x41, 0xc9, 0x5d,
	0xac, 0xa5, 0xa1, 0x88, 0xc8, 0x5a, 0x75, 0xb5, 0x0a, 0xe4, 0xde, 0x5b, 0x3f, 0x46, 0xbf, 0x68,
	0xd9, 0x3f, 0x91, 0x25, 0x5b, 0x85, 0xde, 0x66, 0x9e, 0x9d, 0x7d, 0x76, 0xb4, 0xf3, 0xd3, 0xc2,
	0xb4, 0x10, 0x5c, 0xf2, 0xab, 0xef, 0x6c, 0x8b, 0x54, 0x87, 0xfe, 0x1b, 0x20, 0xdf, 0x0a, 0xcc,
	0xef, 0xb0, 0x2c, 0x53, 0x9e, 0x87, 0xf8, 0xa3, 0xc2, 0x52, 0x92, 0x39, 0x0c, 0x25, 0x7f, 0xc0,
	0xdc, 0xeb, 0x2d, 0x7b, 0x97, 0xe3, 0xd0, 0x24, 0x3e, 0x87, 0x59, 0xab, 0xb6, 0x2c, 0x78, 0x5e,
	0x22, 0x79, 0x0d, 0x50, 0x1a, 0x29, 0x4a, 0x13, 0xbb, 0x63, 0x6c, 0x95, 0xeb, 0x84, 0xbc, 0x84,
	0x71, 0x91, 0xb1, 0x27, 0x14, 0x6a, 0xb5, 0xaf, 0x57, 0x47, 0x46, 0xb8, 0x4e, 0xc8, 0x2b, 0x18,
	0x4a, 0xb6, 0xc9, 0xd0, 0x1b, 0x2c, 0x7b, 0x97, 0x6e, 0xe0, 0xd0, 0x7b, 0x95, 0x85, 0x46, 0xf4,
	0x7f, 0x0e, 0x60, 0xa8, 0x05, 0xf2, 0x1f, 0xf4, 0x6b, 0xef, 0x7e, 0x9a, 0xe8, 0x06, 0x45, 0xb5,
	0x2d, 0xac, 0xa1, 0x49, 0x08, 0x81, 0x23, 0x59, 0x89, 0x5c, 0x9b, 0x9d, 0x84, 0x3a, 0x26, 0x17,
	0xe0, 0x6a, 0xb3, 0x28, 0x66, 0x22, 0x29, 0xbd, 0x23, 0x5d, 0x0f, 0x5a, 0x5a, 0x2b, 0x45, 0x15,
	0xc4, 0x59, 0xb5, 0x89, 0x4c, 0x4f, 0xde, 0x50, 0xef, 0x05, 0x25, 0xdd, 0x6a, 0x85, 0x9c, 0x83,
	0x93, 0x20, 0xcb, 0x50, 0x78, 0x8e, 0x5e, 0xb3, 0x19, 0x59, 0xc2, 0x44, 0x22, 0xdb, 0x46, 0xab,
	0xa8, 0x8c, 0xb9, 0x40, 0xef, 0xd8, 0xec, 0x54, 0xda, 0xea, 0x4e, 0x29, 0x75, 0x45, 0x60, 0x2b,
	0x46, 0xbb, 0x8a, 0xa0, 0x5d, 0xb1, 0x8a, 0x24, 0x97, 0x2c, 0xf3, 0xc6, 0x0d, 0x8f, 0x7b, 0xa5,
	0x34, 0x3c, 0x4c, 0x05, 0x34, 0x3c, 0x4c, 0xc5, 0x7b, 0x98, 0x14, 0x4c, 0xc8, 0x34, 0x4e, 0x0b,
	0x96, 0xcb, 0xd2, 0x73, 0x97, 0x83, 0x4b, 0x37, 0x98, 0xd0, 0xdb, 0x9d, 0x18, 0xb6, 0x2a, 0xc8,
	0x14, 0x06, 0x1b, 0x94, 0xde, 0x44, 0x5b, 0xa9, 0x50, 0x0d, 0xa9, 0xca, 0x53, 0x19, 0xc9, 0xa7,
	0x02, 0xbd, 0x13, 0x33, 0x24, 0x25, 0xdc, 0x3f, 0x15, 0xe8, 0xbf, 0x05, 0xc7, 0x5e, 0xc5, 0xfe,
	0x18, 0x08, 0x1c, 0xe5, 0x6c, 0x8b, 0x76, 0x0a, 0x3a, 0xf6, 0xcf, 0x60, 0xb6, 0xce, 0x78, 0x89,
	0x6d, 0xa4, 0xfc, 0x73, 0x98, 0xb7, 0x65, 0x43, 0x8f, 0xbf, 0x06, 0xb2, 0x16, 0xc8, 0x24, 0x9a,
	0xc9, 0x5b, 0x00, 0x5b, 0xfd, 0xf4, 0xda, 0xfd, 0x3c, 0xb7, 0xdf, 0xaf, 0xdb, 0xf7, 0x23, 0x98,
	0xb5, 0x4c, 0x2c, 0x99, 0x2f, 0x60, 0x64, 0x66, 0x5f, 0x37, 0x7d, 0xac, 0x73, 0x43, 0xe5, 0xee,
	0x80, 0x7e, 0xf7, 0x01, 0x83, 0xdd, 0x01, 0xef, 0x60, 0xfa, 0x95, 0xa7, 0x79, 0xab, 0xc7, 0xbf,
	0xbb, 0xfb, 0x2b, 0x38, 0x6d, 0x94, 0xdb, 0x6e, 0x6a, 0xd6, 0x7b, 0x5d, 0xac, 0xff, 0xea, 0x81,
	0xdb, 0x98, 0x58, 0x17, 0xf1, 0x5c, 0x24, 0x28, 0xec, 0x67, 0x9b, 0x44, 0xa9, 0x86, 0xeb, 0x81,
	0xf9, 0x0f, 0xe2, 0x1a, 0x69, 0x15, 0x44, 0x31, 0xaf, 0x72, 0xa9, 0x99, 0x57, 0x48, 0x2b, 0x69,
	0xad, 0x14, 0x72, 0x01, 0x4e, 0x03, 0x77, 0x37, 0x38, 0xa6, 0x66, 0xc0, 0xa1, 0x95, 0xfd, 0xcf,
	0xf0, 0xff, 0x0d, 0x7b, 0xc0, 0x1b, 0xfe, 0xf8, 0x0f, 0x9f, 0xab, 0x30, 0x50, 0xe6, 0xcf, 0x18,
	0xa8, 0xd8, 0x27, 0x30, 0xdd, 0x39, 0x98, 0x1b, 0x08, 0x7e, 0xf7, 0xc1, 0xfd, 0xc2, 0xb6, 0x78,
	0x87, 0xe2, 0x31, 0x8d, 0x91, 0x7c, 0x04, 0xb7, 0xf1, 0xa0, 0x90, 0x19, 0x3d, 0x7c, 0x8a, 0x16,
	0x73, 0xda, 0xf5, 0xe6, 0x7c, 0x82, 0x49, 0x93, 0x26, 0x32, 0xa7, 0x1d, 0xcc, 0x2d, 0xce, 0x68,
	0x17, 0x72, 0xea, 0xd8, 0x06, 0x2d, 0x64, 0x46, 0x0f, 0x01, 0x5c, 0xcc, 0x69, 0x17, 0x50, 0x01,
	0x8c, 0xeb, 0xb9, 0x92, 0x53, 0xba, 0x8f, 0xc4, 0x82, 0xd0, 0xc3, 0xb1, 0x5f, 0xc1, 0xe8, 0xf9,
	0x22, 0xc8, 0x94, 0xee, 0xdd, 0xea, 0xe2, 0x94, 0xee, 0xdf, 0xd2, 0xc6, 0xd1, 0x2f, 0xf3, 0x87,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xcd, 0xf5, 0xb0, 0xad, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	// Table requests
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	JoinTable(ctx context.Context, in *JoinTableRequest, opts ...grpc.CallOption) (*JoinTableResponse, error)
	MakeMove(ctx context.Context, in *MakeMoveRequest, opts ...grpc.CallOption) (*MakeMoveResponse, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, "/GameService/OpenSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, "/GameService/CloseSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, "/GameService/CreateTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) JoinTable(ctx context.Context, in *JoinTableRequest, opts ...grpc.CallOption) (*JoinTableResponse, error) {
	out := new(JoinTableResponse)
	err := c.cc.Invoke(ctx, "/GameService/JoinTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) MakeMove(ctx context.Context, in *MakeMoveRequest, opts ...grpc.CallOption) (*MakeMoveResponse, error) {
	out := new(MakeMoveResponse)
	err := c.cc.Invoke(ctx, "/GameService/MakeMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	// Table requests
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	JoinTable(context.Context, *JoinTableRequest) (*JoinTableResponse, error)
	MakeMove(context.Context, *MakeMoveRequest) (*MakeMoveResponse, error)
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/OpenSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/CloseSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/CreateTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_JoinTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).JoinTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/JoinTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).JoinTable(ctx, req.(*JoinTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_MakeMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).MakeMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/MakeMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).MakeMove(ctx, req.(*MakeMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _GameService_OpenSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _GameService_CloseSession_Handler,
		},
		{
			MethodName: "CreateTable",
			Handler:    _GameService_CreateTable_Handler,
		},
		{
			MethodName: "JoinTable",
			Handler:    _GameService_JoinTable_Handler,
		},
		{
			MethodName: "MakeMove",
			Handler:    _GameService_MakeMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game.proto",
}
